language: android  
android:
  components:
    - tools
    - build-tools-29.0.2
    - android-28
    - extra-android-m2repository
    - extra-android-support

before_install:
  - cd IPCroid
  - chmod +x gradlew

script:  
  - ./gradlew assembleRelease
